Upstream generation fix for dev environment, Dynamic command result check support for local exchange upgrade.

diff --git a/hex b/hex
--- a/hex
+++ b/hex
@@ -123,6 +123,8 @@ if [[ "$1" == 'dev' ]]; then
         shift
     done
 
+    IS_DEVELOP=true
+
     if [[ "$HEX_CODEBASE_PATH" ]]; then
 
         CONFIG_FILE_PATH=$HEX_CODEBASE_PATH/tools/hex-cli-settings/*
@@ -708,15 +710,23 @@ elif [[ "$1" == "launch" ]]; then
 
         fi
 
-        docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml $LOCAL_COMMAND
-        
-        # Running database init
-        RUN_WITH_VERIFY=false
-        local_database_init start;
+        if command docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml $LOCAL_COMMAND; then
 
-        # Restarting containers after database init jobs.
-        echo "Restarting containers to apply database changes."
-        docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml restart
+             # Running database init
+            RUN_WITH_VERIFY=false
+            local_database_init start;
+
+             # Restarting containers after database init jobs.
+            echo "Restarting containers to apply database changes."
+            docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml restart
+
+
+        else 
+
+            echo "*** hex-cli failed to launch containers. Please review your settings and try again. ***"
+            exit 1;
+       
+        fi
 
         exit 0;
 
