add setconfig support, general wording improvements

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -892,7 +892,7 @@ elif [[ "$1" == "setup" ]]; then
 
         fi
 
-        if command docker ps | grep local_$ENVIRONMENT_EXCHANGE_NAME > /dev/null 2>&1; then
+        if command docker ps -a | grep local_$ENVIRONMENT_EXCHANGE_NAME > /dev/null 2>&1; then
 
             echo "*********************************************"
             printf "\033[91mError: HollaEx CLI detected that the exchange exists on your machine.\033[39m\n"
@@ -1290,7 +1290,7 @@ elif [[ "$1" == "login" ]]; then
         else 
 
             printf "\033[92mSuccessfully authenticated on bitHolla Server.\033[39m\n"
-            echo "Info: Your authentication will be only available for 24 hours."
+            # echo "Info: Your authentication will be only available for 24 hours."
 
             echo $BITHOLLA_ACCOUNT_TOKEN > $HOLLAEX_CLI_INIT_PATH/.token
 
@@ -1339,6 +1339,16 @@ elif [[ "$1" == "login" ]]; then
        | jq '.')
     
     BITHOLLA_USER_EXCHANGE_COUNT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r '.count')
+    
+    # Exit with error if user doesn't have any exchange on the account.
+    if [[ "$BITHOLLA_USER_EXCHANGE_COUNT" == "0" ]]; then
+
+        printf "\n\033[91mError: You don't have any exchange on your account.\033[39m\n"
+        echo "Please go to the bitHolla Dashboard (dash.bitholla.com), and do an exchange configuration first."
+        
+        exit 1;
+
+    fi
 
     # Subtracting 1 from total count due to the array starts from 0, not from 1.
     BITHOLLA_USER_EXCHANGE_COUNT=$((BITHOLLA_USER_EXCHANGE_COUNT-1))
@@ -1476,7 +1486,7 @@ elif [[ "$1" == "logout" ]]; then
 
     source $SCRIPTPATH/tools_generator.sh
     load_config_variables;
-
+    
     if [[ ! "$HOLLAEX_SECRET_ACTIVATION_CODE" ]]; then
 
         printf "\033[91mFailed to read pre-bound Activation code.\033[39m\n"
@@ -1494,6 +1504,13 @@ elif [[ "$1" == "logout" ]]; then
     if [[ "$answer" = "${answer#[Yy]}" ]]; then
         echo "Exiting..."
         exit 0;
+    fi
+
+    # Removing the login token
+    if [[ -f "$HOLLAEX_CLI_INIT_PATH/.token" ]]; then
+
+        rm $HOLLAEX_CLI_INIT_PATH/.token
+    
     fi
 
     if command sed -i.bak "s/HOLLAEX_CONFIGMAP_API_NAME=.*/HOLLAEX_CONFIGMAP_API_NAME=/" $CONFIGMAP_FILE_PATH; then
@@ -2112,7 +2129,7 @@ elif [[ "$1" == "stop" ]]; then
         fi
 
         # Only tries to attempt remove ingress rules from Kubernetes if it exists.
-        if command kubectl get ingress -n $ENVIRONMENT_EXCHANGE_NAME > /dev/null; then
+        if ! command kubectl get ingress -n $ENVIRONMENT_EXCHANGE_NAME > /dev/null 2>&1; then
         
             echo "Removing $HOLLAEX_CONFIGMAP_API_NAME ingress rule on the cluster."
             kubectl delete -f $TEMPLATE_GENERATE_PATH/kubernetes/config/$ENVIRONMENT_EXCHANGE_NAME-ingress.yaml
@@ -3279,12 +3296,14 @@ elif [[ "$1" == "web" ]]; then
 
             if [[ ! -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf" ]] || [[ ! -s "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf" ]]; then
 
-                if [[ -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]]; then
+                if [[ -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]] || [[ -s "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]]; then
 
                     echo "Restoring old web Nginx configuration file"
                     cp -f $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf
 
-                else 
+                    rm $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf
+
+                else
 
                     echo "Generating web Nginx configuration file"
                     generate_hollaex_web_local_nginx_conf
@@ -3445,12 +3464,14 @@ elif [[ "$1" == "web" ]]; then
 
             if [[ ! -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf" ]] || [[ ! -s "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf" ]]; then
 
-                if [[ -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]]; then
+                if [[ -f "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]] || [[ -s "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf" ]]; then
 
                     echo "Restoring old web Nginx configuration file"
                     cp -f $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/web.conf
 
-                else 
+                    rm $TEMPLATE_GENERATE_PATH/local/nginx/conf.d/.web.conf
+
+                else
 
                     echo "Generating web Nginx configuration file"
                     generate_hollaex_web_local_nginx_conf
@@ -3969,6 +3990,12 @@ elif [[ "$1" == "toolbox" ]]; then
                 SET_ACTIVATION_CODE=true
                 TOOLBOX_ENABLE=true
                 echo "HollaEx CLI will update your activation code for the exchange."
+                shift; continue
+                ;;
+            --set_config)
+                SET_CONFIG=true
+                TOOLBOX_ENABLE=true
+                echo "Override database-stored cosntants with local configmap-stored values."
                 shift; continue
                 ;;
              --connect_database)
@@ -4752,6 +4779,59 @@ elif [[ "$1" == "toolbox" ]]; then
             echo "Make sure to run 'hollaex restart' to fully apply it."
 
         fi
+
+    elif [[ "$SET_CONFIG" ]]; then
+
+        function toolbox_set_config_confirm_message() {
+
+            echo "Warning: This command is not recommended for most of users in most of use cases."
+            echo "This command would completely override your database to update values with local settings."
+            echo "Are you sure you want to update database-stored constatns with your local configmap values? (y/N)"
+            read answer
+
+            if [[ "$answer" = "${answer#[Yy]}" ]] ;then
+                echo "Exiting..."
+                exit 0;
+            fi
+
+        }
+
+        if [[ "$USE_KUBERNETES" ]]; then 
+
+            check_kubernetes_dependencies;
+        
+            echo "*********************************************"
+            echo "Verifying current KUBECONFIG on the machine"
+            kubectl get nodes
+            echo "*********************************************"
+
+            toolbox_set_config_confirm_message;
+
+            echo "Generating Kubernetes Configmap."
+            generate_kubernetes_configmap;
+
+            echo "Generating Kubernetes Secret."
+            generate_kubernetes_secret;
+
+             echo "Applying configmap on the namespace."
+            kubectl apply -f $TEMPLATE_GENERATE_PATH/kubernetes/config/$ENVIRONMENT_EXCHANGE_NAME-configmap.yaml
+            
+            echo "Applying secret on the namespace."
+            kubectl apply -f $TEMPLATE_GENERATE_PATH/kubernetes/config/$ENVIRONMENT_EXCHANGE_NAME-secret.yaml
+
+            set_config_exec;
+            
+
+        elif [[ ! "$USE_KUBERNETES" ]]; then 
+        
+            check_docker_compose_dependencies; 
+
+            toolbox_set_config_confirm_message;
+
+            set_config_exec;
+
+        fi
+
 
     elif [[ "$CONNECT_DATABASE" ]]; then
 
