docker compose to docker-compose standalone command sets

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -36,27 +36,32 @@ LOCAL_DEPLOYMENT_MODE='all'
 
 GENERATE_PASSWORDS=false
 
-echo "Checking docker compose availability..."
-docker compose version
+function check_docker_compose_is_installed() {
 
-# Checking docker compose is installed on this machine.
-if [[ $? -ne 0 ]] ; then
+    echo "Checking docker-compose availability..."
+    docker-compose version
 
-    echo -e "\n\033[91mError: HollaEx CLI could not detect Docker Compose on this machine. Please install Docker Compose before proceeding.\033[39m\n"
-    echo "To install the core dependencies, including Docker Compose, you can run: \`bash install.sh\`."
-    echo -e "Alternatively, you can manually install Docker Compose by following the instructions at: https://docs.docker.com/compose/install/linux/.\n"
+    # Checking docker compose is installed on this machine.
+    if [[ $? -ne 0 ]] ; then
 
-    echo -e "Warning: HollaEx CLI v3+ only supports the Docker Compose Plugin (the 'docker compose' command without a dash) and not the standalone binary ('docker-compose').\n"
-    exit 1
+        echo -e "\n\033[91mError: HollaEx CLI could not detect Docker Compose on this machine. Please install Docker Compose before proceeding.\033[39m\n"
+        echo "To install the core dependencies, including Docker Compose, you can run: \`bash install.sh\`."
+        echo -e "Alternatively, you can manually install Docker Compose by following the instructions at: https://docs.docker.com/compose/install/standalone/.\n"
 
-fi
+        exit 1
+
+    fi
+  
+}
+
+check_docker_compose_is_installed;
 
 # Docker compose v1 prefixes
 DOCKER_COMPOSE_NAME_PREFIX='local_'
 DOCKER_COMPOSE_CONTAINER_NUMBER_CONNECTOR="_"
 
 # Docker compose v2+ compatibility prefiexes
-if command docker compose version > /dev/null; then
+if command docker-compose version > /dev/null; then
 
     # export DOCKER_COMPOSE_NAME_PREFIX="server-"
     DOCKER_COMPOSE_NAME_PREFIX='local-'
@@ -400,7 +405,7 @@ if [[ "$1" == "dev" ]]; then
     
         local_database_init start;
 
-        docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
+        docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
 
         exit 0;
 
@@ -522,7 +527,7 @@ if [[ "$1" == "dev" ]]; then
 
             fi
 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d  
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d  
             
             echo "Installing npm packages for /plugins"
             docker exec ${DOCKER_COMPOSE_NAME_PREFIX}${ENVIRONMENT_EXCHANGE_NAME}-server-api_1 bash -c '
@@ -532,17 +537,17 @@ if [[ "$1" == "dev" ]]; then
 
             hollaex dev --database_init
         
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
 
             hollaex_setup_finalization;
 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
             
             
         elif [[ "$HOLLAEX_DEV_RESTART" ]]; then
 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml stop
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml stop
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d
 
             if [[ ! "$HOLLAEX_DEV_SETUP" ]]; then
 
@@ -555,7 +560,7 @@ if [[ "$1" == "dev" ]]; then
 
         else 
 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml $LOCAL_COMMAND
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml $LOCAL_COMMAND
 
         fi
 
@@ -1391,7 +1396,7 @@ elif [[ "$1" == "setup" ]]; then
             
         # fi
 
-        if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d; then
+        if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d; then
             
             sleep 5
             
@@ -1421,7 +1426,7 @@ elif [[ "$1" == "setup" ]]; then
 
             fi
 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
 
             if [[ "$HOLLAEX_NETWORK_SETUP" ]]; then
 
@@ -2757,7 +2762,7 @@ elif [[ "$1" == "start" ]]; then
         
         fi
 
-        if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d; then
+        if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d; then
         
 
             if [[ "$HOLLAEX_NETWORK_START" ]]; then 
@@ -2777,7 +2782,7 @@ elif [[ "$1" == "start" ]]; then
                 if command docker ps | grep nginx > /dev/null 2>&1; then
                 
                     echo "Restarting Nginx..."
-                    if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml restart; then
+                    if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml restart; then
                     
                         printf "\n\033[92mSuccessfully restarted the Nginx\033[39m\n"
             
@@ -2994,7 +2999,7 @@ elif [[ "$1" == "scale" ]]; then
         fi
 
         # Running docker-compose scale command.
-        if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d --no-recreate --scale $HOLLAEX_SCALE_TARGET_CONVERTED=$HOLLAEX_SCALE_TARGET_REPLICAS; then
+        if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d --no-recreate --scale $HOLLAEX_SCALE_TARGET_CONVERTED=$HOLLAEX_SCALE_TARGET_REPLICAS; then
             
             # Nginx Reload
             docker exec -it $(docker ps | grep $ENVIRONMENT_EXCHANGE_NAME-prod-nginx | cut -f1 -d " ") nginx -s reload
@@ -3826,7 +3831,7 @@ elif [[ "$1" == "stop" ]]; then
 
         fi
 
-        if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml stop; then
+        if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml stop; then
 
             if [[ "$HOLLAEX_NETWORK_STOP" ]]; then 
 
@@ -4860,14 +4865,14 @@ elif [[ "$1" == "terminate" ]]; then
         # Remove web server together if it exists.
         if [[ -f "$HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml" ]] ; then
 
-            docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down 
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml down
+            docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down 
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml down
 
         fi
 
         
 
-        docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml down -v --remove-orphans
+        docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml down -v --remove-orphans
 
         hollaex_ascii_exchange_has_been_terminated;
         
@@ -5243,10 +5248,10 @@ elif [[ "$1" == "web" ]]; then
 
             # apply_nginx_root_domain_to_web
 
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up --build -d; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up --build -d; then
 
                 echo "Starting the Nginx..."
-                if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml up -d; then
+                if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml up -d; then
                 
                     printf "\n\033[92mSuccessfully started the Nginx\033[39m\n"
         
@@ -5433,7 +5438,7 @@ elif [[ "$1" == "web" ]]; then
                 
             # fi
 
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d; then
 
                 # echo "Reloading Nginx..."
                 # if command docker exec $(docker ps | grep $ENVIRONMENT_EXCHANGE_NAME-prod-nginx | cut -f1 -d " ") nginx -s reload; then
@@ -5449,7 +5454,7 @@ elif [[ "$1" == "web" ]]; then
                 # fi
 
                 echo "Starting the Nginx..."
-                docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml up -d
+                docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml up -d
 
                 hollaex_ascii_web_server_is_up;
 
@@ -5545,7 +5550,7 @@ elif [[ "$1" == "web" ]]; then
             # cp -f $HOLLAEX_CLI_INIT_PATH/nginx/conf.d/web.conf $HOLLAEX_CLI_INIT_PATH/nginx/conf.d/.web.conf
             # rm $HOLLAEX_CLI_INIT_PATH/nginx/conf.d/web.conf
 
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client stop; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client stop; then
 
                 # echo "Reloading Nginx..."
                 # if command docker exec $(docker ps | grep $ENVIRONMENT_EXCHANGE_NAME-prod-nginx | cut -f1 -d " ") nginx -s reload; then
@@ -5562,7 +5567,7 @@ elif [[ "$1" == "web" ]]; then
                 echo "To bring it up, Please run 'hollaex web --start' command".
 
                 echo "Stopping the Nginx..."
-                docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml stop
+                docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml stop
 
 
             else 
@@ -5713,10 +5718,10 @@ elif [[ "$1" == "web" ]]; then
                 
             # fi
 
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client restart; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client restart; then
 
                 echo "Restarting Nginx..."
-                if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml restart; then
+                if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml restart; then
                 
                     printf "\n\033[92mSuccessfully restarted the Nginx\033[39m\n"
         
@@ -5842,7 +5847,7 @@ elif [[ "$1" == "web" ]]; then
         else 
                 
                 update_local_docker_compose_web;
-                docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d;
+                docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d;
 
         fi
 
@@ -5912,10 +5917,10 @@ elif [[ "$1" == "web" ]]; then
 
             fi
 
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down --remove-orphans; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down --remove-orphans; then
 
                 echo "Stopping Nginx..."
-                if command docker compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml stop; then
+                if command docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/nginx/docker-compose.yaml stop; then
                 
                     printf "\n\033[92mSuccessfully stopped the Nginx\033[39m\n"
         
@@ -5991,10 +5996,10 @@ elif [[ "$1" == "web" ]]; then
 
             # generate_local_docker_compose_for_web;
 
-            docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down
+            docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client down
 
             # Running docker-compose scale command.
-            if command docker compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d --no-recreate --scale $ENVIRONMENT_EXCHANGE_NAME-web=$HOLLAEX_WEB_SCALE_TARGET_REPLICAS; then
+            if command docker-compose -f $HOLLAEX_CLI_INIT_PATH/web/docker-compose.yaml -p client up -d --no-recreate --scale $ENVIRONMENT_EXCHANGE_NAME-web=$HOLLAEX_WEB_SCALE_TARGET_REPLICAS; then
                 
                 # Nginx Reload
                 # docker exec -it $(docker ps | grep $ENVIRONMENT_EXCHANGE_NAME-prod-nginx | cut -f1 -d " ") nginx -s reload
@@ -6436,7 +6441,7 @@ elif [[ "$1" == "toolbox" ]]; then
             # generate_local_docker_compose $ENVIRONMENT_EXCHANGE_RUN_MODE
 
             echo "Restarting containers..."
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml up -d
 
             exit 0;
 
@@ -6779,7 +6784,7 @@ elif [[ "$1" == "toolbox" ]]; then
             docker exec ${DOCKER_COMPOSE_NAME_PREFIX}${ENVIRONMENT_EXCHANGE_NAME}-server${CONTAINER_PREFIX[0]}${DOCKER_COMPOSE_CONTAINER_NUMBER_CONNECTOR}1 node tools/dbs/flushRedis.js
 
             echo "Restarting all workload containers..."
-            docker compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
+            docker-compose -f ${HOLLAEX_CLI_INIT_PATH}/server/docker-compose-prod.yaml restart
 
             sleep 10;
 
