- Version update to v1.7 - 'hollaex import' command support to import settings files into user's HollaEx Kit. - Add coin support with stored coin details at configmap.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -22,7 +22,7 @@ function print_usage() {
 Usage : 
     hollaex [ init ] [ setup ] [ start ] [ restart ] [ stop ] [ build ] [ upgrade ] [ terminate ] [ web ] [ toolbox ] [ status ] [ logs ] [ version ] (--flags)
 
-General Flags (Except for 'hollaex init'):
+General Flags (Except for 'hollaex init', 'hollaex import'):
     --path, Manually pointing HollaEx Kit path. Should be always absolute path.
     --kube, Set HollaEx CLI to target Kubernetes. Make sure to setup your local kubectl before using it.
     --skip, Run command without user's double confirmation.
@@ -32,6 +32,9 @@ Options:
 
     setup: Setup the exchange for the first launch.
         --reconfigure, Reconfigure basic settings such as Server domain or Activation Code.
+    
+    import: Import settings files generated by using bitHolla Dashboard (dash.bitholla.com).
+        --file, Path of file or directory where settings files are stored.
 
     start: Start the exchange which already been configured by 'hollaex setup' command.
 
@@ -43,6 +46,7 @@ Options:
     
     upgrade: Upgrade the exchange to new version.
         --version, Version number of HollaEx Core to upgrade.
+        --user-image-registry, Specify Docker registry and version (tag) for the user HollaEx Core image.
 
     terminate: Terminate the existing exchange. THIS COMMAND WILL COMPLETELY REMOVE YOUR EXCHANGE.
       
@@ -633,13 +637,13 @@ elif [[ "$1" == "setup" ]]; then
 
         hollaex_setup_finalization;
 
+        hollaex_ascii_exchange_has_been_setup;
+
         echo "Shutting down the exchange..."
         hollaex stop --kube --skip
         
         echo "Finalizing the exchange setup..."
         sleep 5;
-
-        hollaex_ascii_exchange_has_been_setup;
 
         exit 0;
 
@@ -761,13 +765,154 @@ elif [[ "$1" == "setup" ]]; then
         
         hollaex_setup_finalization;
 
+        hollaex_ascii_exchange_has_been_setup;
+
         echo "Finalizing the exchange setup..."
         sleep 5;
 
-        hollaex_ascii_exchange_has_been_setup;
-
         exit 0;
 
+    fi
+
+elif [[ "$1" == "import" ]]; then
+
+    # while true; do
+    #     [[ $# -eq 0 ]] && break
+    #     case $1 in
+    #         --file)
+    #             shift 
+    #             case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+    #             HOLLAEX_IMPORT_PATH=$1
+    #             echo "Your file / directory path to import : $HOLLAEX_IMPORT_PATH."
+    #             if [[ "$2" ]]; then
+    #                 echo "Your second file / directory path to import : $HOLLAEX_IMPORT_PATH_2."
+    #             fi
+    #             shift; continue
+    #             ;;
+    #         --*) 
+    #             err_msg "Invalid option: $1"
+    #             print_usage;
+    #             exit 1;
+    #             ;;
+    #     esac
+    #     shift
+    # done
+
+    HOLLAEX_IMPORT_PATH_INPUT=$@
+    IFS=' ' read -ra HOLLAEX_IMPORT_PATH <<< "$HOLLAEX_IMPORT_PATH_INPUT"    #Convert string to array
+
+    if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        HOLLAEX_CLI_INIT_PATH=$(pwd)
+        CONFIG_FILE_PATH=$(pwd)/settings/*
+        IMPORT_FILE_PATH=$(pwd)/settings
+        TEMPLATE_GENERATE_PATH=$(pwd)/templates
+        INIT_PATH_CHECK=$(pwd)/.hollaex
+
+    fi
+
+    if [[ "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        CONFIG_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings/*
+        IMPORT_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings
+        TEMPLATE_GENERATE_PATH=$HOLLAEX_CLI_INIT_PATH/templates
+        INIT_PATH_CHECK=$HOLLAEX_CLI_INIT_PATH/.hollaex
+        
+    fi
+    
+
+
+    #Quit if necessary flags are missing
+    if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
+
+        printf "\033[91mFailed to detect HollaEx Kit directory! Please re-check your path.\033[39m\n"
+        print_usage;
+        exit 1;
+
+    fi
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+        source $i
+    done;
+    
+    source $SCRIPTPATH/tools_generator.sh
+    load_config_variables;
+
+    if [[ ! -d "$HOLLAEX_CLI_INIT_PATH/.old" ]]; then
+
+        mkdir $HOLLAEX_CLI_INIT_PATH/.old
+
+    fi
+
+# Storing current CURRENCIES and PARIS
+cat > $HOLLAEX_CLI_INIT_PATH/.old/old-currencies-and-pairs <<EOL
+
+OLD_CURRENCIES=$(echo $HOLLAEX_CONFIGMAP_CURRENCIES)
+OLD_PAIRS=$(echo $HOLLAEX_CONFIGMAP_PAIRS)
+
+EOL
+
+    rm $CONFIG_FILE_PATH
+
+    for i in ${HOLLAEX_IMPORT_PATH[@]}; do
+
+        if [[ -d "$i" ]]; then
+            
+            if command cp $i/* $IMPORT_FILE_PATH; then
+
+                IS_IMPORT_SUCCESS=true
+            
+            else 
+
+                IS_IMPORT_SUCCESS=false
+            
+            fi
+
+        elif [[ -f "$i" ]]; then
+
+            if command cp $i $IMPORT_FILE_PATH; then
+
+                IS_IMPORT_SUCCESS=true
+            
+            else 
+
+                IS_IMPORT_SUCCESS=false
+            
+            fi
+        
+        fi
+
+    done;
+
+    if [[ -d "$HOLLAEX_IMPORT_PATH" ]]; then
+        
+        if command cp $HOLLAEX_IMPORT_PATH/* $IMPORT_FILE_PATH; then
+
+            IS_IMPORT_SUCCESS=true
+        
+        fi
+
+    elif [[ -f "$HOLLAEX_IMPORT_PATH" ]]; then
+
+        if command cp $HOLLAEX_IMPORT_PATH $IMPORT_FILE_PATH; then
+
+            IS_IMPORT_SUCCESS=true
+        
+        fi
+    
+    fi
+
+    if [[ "$IS_IMPORT_SUCCESS" == true ]]; then 
+
+        echo "Your settings files (or directory) has been imported into your HollaEx Kit!"
+
+    else 
+
+        echo "Failed to import your files into HollaEx Kit."
+        echo "Please confirm that you passed the correct path of your settings files, and try again."
+
+        exit 1;
+    
     fi
 
 
@@ -2116,7 +2261,7 @@ elif [[ "$1" == "terminate" ]]; then
         fi
 
         echo "$HOLLAEX_CONFIGMAP_API_NAME ($HOLLAEX_CONFIGMAP_API_HOST) has been successfully terminated. If there's an issue, please review the logs and try it again."
-        
+
         exit 0;
 
     fi
