Docker daemon status check at 'hollaex setup', Nginx reloading after local scaling.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -570,6 +570,8 @@ elif [[ "$1" == "setup" ]]; then
 
     system_dependencies_check;
 
+    check_docker_daemon_status;
+
     if [[ ! "$IGNORE_COMPATIBILITY_CHECK" ]]; then 
 
         # Check Kit version compatibility range.
@@ -2305,11 +2307,6 @@ elif [[ "$1" == "scale" ]]; then
                 echo "Target Replicas: $HOLLAEX_SCALE_TARGET_REPLICAS."
                 shift; continue
                 ;;
-            --ignore_settings)
-                IGNORE_SETTINGS=true
-                echo "HollaEx CLI will ignore local settings update on restart."
-                shift; continue
-                ;;
             --kube)
                 USE_KUBERNETES=true
                 echo "HollaEx CLI will use your Kubernetes cluster as a target."
@@ -2364,14 +2361,6 @@ elif [[ "$1" == "scale" ]]; then
 
      source $SCRIPTPATH/tools_generator.sh
 
-    # Update random secrets if env generation is enabled.
-    if [[ ! "$IGNORE_SETTINGS" ]]; then 
-
-        #Regenerate random secrets
-        update_random_values_to_config;
-
-    fi
-
     for i in ${CONFIG_FILE_PATH[@]}; do
         source $i
     done;
@@ -2399,23 +2388,17 @@ elif [[ "$1" == "scale" ]]; then
 
     if [[ "$HOLLAEX_SCALE_TARGET" ]]; then
 
-        for i in "${SUPPORTED_TARGETS[@]}"
-            do
-                if [ "$i" == "$HOLLAEX_SCALE_TARGET" ] ; then
-                    
-                    export HOLLAEX_SCALE_TARGET_CONVERTED="${ENVIRONMENT_EXCHANGE_NAME}-server-${HOLLAEX_SCALE_TARGET}"
-                    break;
-                
-                else 
+        if ! command printf '%s\n' ${SUPPORTED_TARGETS[@]} | grep $HOLLAEX_SCALE_TARGET > /dev/null; then
 
-                    echo "Error: The specified target $HOLLAEX_SCALE_TARGET is not supported for scaling."
-                    echo "Supported targets: ${SUPPORTED_TARGETS[@]}."
-                    echo "Please try it again."
+            echo "Error: The specified target $HOLLAEX_SCALE_TARGET is not supported for scaling."
+            echo "Supported targets: ${SUPPORTED_TARGETS[@]}."
+            echo "Please try it again."
 
-                    exit 1;
+            exit 1;
 
-                fi
-        done
+        fi 
+
+        export HOLLAEX_SCALE_TARGET_CONVERTED="${ENVIRONMENT_EXCHANGE_NAME}-server-${HOLLAEX_SCALE_TARGET}"
 
     else
 
@@ -2508,13 +2491,6 @@ elif [[ "$1" == "scale" ]]; then
         if [[ ! -d "$TEMPLATE_GENERATE_PATH/local/nginx/conf.d" ]]; then
             mkdir $TEMPLATE_GENERATE_PATH/local/nginx/conf.d;
         fi
-        
-        if [[ "$ENVIRONMENT_DOCKER_COMPOSE_GENERATE_NGINX_UPSTREAM" == true ]]; then
-
-            echo "Generating Nginx upstream conf"
-            generate_nginx_upstream;
-        
-        fi
 
         # Checking that the existing docker-compose file got the host port bound specifications.
         if command cat $TEMPLATE_GENERATE_PATH/local/${ENVIRONMENT_EXCHANGE_NAME}-docker-compose.yaml | grep -e "10010" -e "10080" > /dev/null 2>&1; then
@@ -2525,7 +2501,10 @@ elif [[ "$1" == "scale" ]]; then
         fi
 
         # Running docker-compose scale command.
-        if command docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml scale $HOLLAEX_SCALE_TARGET_CONVERTED=$HOLLAEX_SCALE_TARGET_REPLICAS; then
+        if command docker-compose -f $TEMPLATE_GENERATE_PATH/local/$ENVIRONMENT_EXCHANGE_NAME-docker-compose.yaml up -d --scale $HOLLAEX_SCALE_TARGET_CONVERTED=$HOLLAEX_SCALE_TARGET_REPLICAS; then
+            
+            # Nginx Reload
+            docker exec -it $(docker ps | grep $ENVIRONMENT_EXCHANGE_NAME-nginx | cut -f1 -d " ") nginx -s reload
 
             echo "Target $HOLLAEX_SCALE_TARGET has been successfully scaled to $HOLLAEX_SCALE_TARGET_REPLICAS."
         
