CLI v2.3.0

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -1189,7 +1189,7 @@ elif [[ "$1" == "init" ]]; then
             
             else 
 
-                if ! command xdg-open https://dash.hollaex.com/signup; then 
+                if ! command xdg-open https://dash.hollaex.com/signup > /dev/null 2>&1; then 
 
                     echo "Error: Your system does not support xdg-open compatible browser."
                     echo "Please open HollaEx Dashboard (https://dash.hollaex.com/signup) by yourself, and continue to sign-up."
@@ -1281,6 +1281,8 @@ elif [[ "$1" == "init" ]]; then
             --request POST \
             --data "{\"email\": \"${hollaexAdminEmail}\", \"password\": \"${hollaexAdminPassword}\", \"exchange_name\": \"${hollaexExchangeName}\"}" \
             $hollaexAPIURL/v2/network/exchange)
+
+        echo $HOLLAEX_INIT_REQUEST
 
         HOLLAEX_INIT_REQUEST_RESPONSE=$(echo $HOLLAEX_INIT_REQUEST | cut -f1 -d ";")
         HOLLAEX_INIT_REQUEST_HTTP_CODE=$(echo $HOLLAEX_INIT_REQUEST | cut -f2 -d ";")
@@ -6763,7 +6765,6 @@ elif [[ "$1" == "toolbox" ]]; then
             export PGPASSWORD=$HOLLAEX_SECRET_DB_PASSWORD
             export PGDATABASE=$HOLLAEX_SECRET_DB_NAME
             export PGHOST=localhost
-            export PGPORT=5433
 
             if ! command pg_restore --verbose --clean -d $PGDATABASE $RESTORE_POSTGRES_DUMP_PATH; then 
 
@@ -8574,7 +8575,12 @@ elif [[ "$1" == "docs" ]]; then
     
     else 
 
-        xdg-open $HOLLAEX_DOCS_URL
+        if ! command xdg-open $HOLLAEX_DOCS_URL > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_DOCS_URL) through your browser by yourself."
+
+        fi
 
     fi
 
@@ -8588,7 +8594,12 @@ elif [[ "$1" == "forum" ]]; then
     
     else 
 
-        xdg-open $HOLLAEX_FORUM_URL
+        if ! command xdg-open $HOLLAEX_FORUM_URL > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_FORUM_URL) through your browser by yourself."
+
+        fi
 
     fi
 
@@ -8602,7 +8613,12 @@ elif [[ "$1" == "discord" ]]; then
     
     else 
 
-        xdg-open $HOLLAEX_DISCORD_URL
+        if ! command xdg-open $HOLLAEX_DISCORD_URL > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_DISCORD_URL) through your browser by yourself."
+
+        fi
 
     fi 
 
@@ -8616,7 +8632,12 @@ elif [[ "$1" == "bug" ]] || [[ "$1" == "bug-report" ]]; then
     
     else
 
-        xdg-open $HOLLAEX_GITHUB_ISSUES_NEW_URL
+         if ! command xdg-open $HOLLAEX_GITHUB_ISSUES_NEW_URL > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_GITHUB_ISSUES_NEW_URL) through your browser by yourself."
+
+        fi
 
     fi 
 
@@ -8630,7 +8651,12 @@ elif [[ "$1" == "xht-market" ]]; then
     
     else 
 
-        xdg-open $HOLLAEX_TRADE_XHT_URL
+        if ! command xdg-open $HOLLAEX_TRADE_XHT_URL > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_TRADE_XHT_URL) through your browser by yourself."
+
+        fi
 
     fi
 
@@ -8650,7 +8676,12 @@ elif [[ "$1" == "trade" ]]; then
     
     else 
 
-        xdg-open $HOLLAEX_CONFIGMAP_DOMAIN
+        if ! command xdg-open $HOLLAEX_CONFIGMAP_DOMAIN > /dev/null 2>&1; then
+
+            echo "Error: Your system does not support xdg-open compatible browser."
+            echo "Please open the website ($HOLLAEX_CONFIGMAP_DOMAIN) through your browser by yourself."
+
+        fi 
 
     fi
 
