hollaex import export db backups command

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -1949,6 +1949,10 @@ elif [[ "$1" == "import" ]]; then
                 TARGET_AWS_S3_BUCKET=$1
                 shift; continue
                 ;;
+            --db_backup)
+                IS_DB_BACKUP=true
+                shift; continue
+                ;;
             --*) 
                 err_msg "Invalid option: $1"
                 print_usage;
@@ -2034,6 +2038,39 @@ EOL
             export ENVIRONMENT_EXCHANGE_NAME=$exchangeNameParsed
 
         fi 
+
+        if [[ "$IS_DB_BACKUP" ]]; then 
+
+            if [[ ! -d $HOLLAEX_CLI_INIT_PATH/backups ]]; then
+
+                echo "Creating '/backups' folder on HollaEx Kit directory"
+                mkdir $HOLLAEX_CLI_INIT_PATH/backups
+
+            fi
+
+            LATEST_DB_DUMP_FILE="$(aws s3 ls $TARGET_AWS_S3_BUCKET/backup/$ENVIRONMENT_EXCHANGE_NAME-postgres --recursive | sort | tail -n 1 | awk '{print $4}')"
+            LATEST_DB_DUMP_FILE_NAME=$(echo $LATEST_DB_DUMP_FILE | cut -f3 -d "/")
+            echo "Latest DB dump file: $LATEST_DB_DUMP_FILE_NAME"
+
+            echo "Pulling the db backup file from s3://$TARGET_AWS_S3_BUCKET/$LATEST_DB_DUMP_FILE AWS S3 bucket."
+            if command aws s3 cp s3://$TARGET_AWS_S3_BUCKET/$LATEST_DB_DUMP_FILE $HOLLAEX_CLI_INIT_PATH/backups/$LATEST_DB_DUMP_FILE_NAME; then
+
+                printf "\033[92mYour backup file has been downloaded at $HOLLAEX_CLI_INIT_PATH/backups.\033[39m\n"
+                echo "If you are going to run a db restore job, please run the command below."
+                echo "'hollaex toolbox --restore backups/$LATEST_DB_DUMP_FILE_NAME."
+
+            else 
+
+                echo "Error: Failed to pull the settings files from s3://$TARGET_AWS_S3_BUCKET/$LATEST_DB_DUMP_FILE."
+                echo "Please check the error logs and try again."
+
+                exit 1;
+
+            fi 
+
+            exit 0;
+
+        fi
 
         mkdir -p $HOLLAEX_CLI_INIT_PATH/.settings-temp
 
@@ -2206,6 +2243,10 @@ elif [[ "$1" == "export" ]]; then
                 TARGET_AWS_S3_BUCKET=$1
                 shift; continue
                 ;;
+            --db_backup)
+                IS_DB_BACKUP=true
+                shift; continue
+                ;;
             --*) 
                 err_msg "Invalid option: $1"
                 print_usage;
@@ -2283,7 +2324,39 @@ elif [[ "$1" == "export" ]]; then
 
             export ENVIRONMENT_EXCHANGE_NAME=$exchangeNameParsed
 
-        fi 
+        fi
+
+        if [[ "$IS_DB_BACKUP" ]]; then 
+
+            if [[ ! -d $HOLLAEX_CLI_INIT_PATH/backups ]]; then
+
+                echo "Error: You don't have any db dumps stored on your HollaEx Kit."
+                echo "Run 'hollaex toolbox --backup' to get the dump file first."
+
+                exit 1;
+
+            fi
+
+            LATEST_DB_DUMP_FILE="$(ls backups/ | sort | tail -n 1)"
+            echo "Latest DB dump file: $LATEST_DB_DUMP_FILE"
+
+            echo "Pushing the db backup file to s3://$TARGET_AWS_S3_BUCKET/backup/$ENVIRONMENT_EXCHANGE_NAME-postgres/$LATEST_DB_DUMP_FILE AWS S3 bucket."
+            if command aws s3 cp backups/$LATEST_DB_DUMP_FILE s3://$TARGET_AWS_S3_BUCKET/backup/$ENVIRONMENT_EXCHANGE_NAME-postgres/$LATEST_DB_DUMP_FILE; then
+
+                printf "\033[92mYour backup file has been uploaded at s3://$TARGET_AWS_S3_BUCKET.\033[39m\n"
+            
+            else 
+
+                echo "Error: Failed to push the db dump at s3://$TARGET_AWS_S3_BUCKET"
+                echo "Please check the error logs and try again."
+
+                exit 1;
+
+            fi 
+
+            exit 0;
+
+        fi
 
         echo "Pushing the settings files to s3://$TARGET_AWS_S3_BUCKET/hollaex-kit-settings/$ENVIRONMENT_EXCHANGE_NAME AWS S3 bucket."
         if ! command aws s3 cp --recursive $HOLLAEX_CLI_INIT_PATH/settings s3://$TARGET_AWS_S3_BUCKET/hollaex-kit-settings/$ENVIRONMENT_EXCHANGE_NAME; then
