- 'hollaex status' command support - 'hollaex logs' command support

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -20,7 +20,7 @@ function print_usage() {
 /bin/cat << EOF
 
 Usage : 
-    hollaex [ init ] [ setup ] [ start ] [ stop ] [ upgrade ] [ terminate ] [ web ] [ toolbox ] [ version ] (--flags)
+    hollaex [ init ] [ setup ] [ start ] [ stop ] [ upgrade ] [ terminate ] [ web ] [ toolbox ] [ status ] [ logs ] [ version ] (--flags)
 
 General Flags (Except for 'hollaex init'):
     --path, Manually pointing HollaEx Kit path. Should be always absolute path.
@@ -1678,9 +1678,9 @@ elif [[ "$1" == "upgrade" ]]; then
         
     fi
 
-    # echo "Upgrading HollaEx CLI to latest..."
-    # curl -L https://raw.githubusercontent.com/bitholla/hollaex-cli/master/install.sh | bash;
-    # sleep 5;
+    echo "Upgrading HollaEx CLI to latest..."
+    curl -L https://raw.githubusercontent.com/bitholla/hollaex-cli/master/install.sh | bash;
+    sleep 5;
 
     if [[ "$USE_KUBERNETES" ]]; then
 
@@ -3177,8 +3177,247 @@ elif [[ "$1" == "toolbox" ]]; then
     fi
 
 
-elif [[ "$1" == "version" ]]; then
+elif [[ "$1" == "status" ]]; then
+
+     while true; do
+        [[ $# -eq 0 ]] && break
+        case $1 in
+            --path)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                HOLLAEX_CLI_INIT_PATH=$1
+                echo "Your HollaEx Kit Path : $HOLLAEX_CLI_INIT_PATH."
+                shift; continue
+                ;;
+            --kube)
+                USE_KUBERNETES=true
+                echo "HollaEx CLI will use your Kubernetes cluster as a target."
+                shift; continue
+                ;;
+            --*) 
+                err_msg "Invalid option: $1"
+                print_usage;
+                exit 1;
+                ;;
+        esac
+        shift
+     done
+
+    if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        HOLLAEX_CLI_INIT_PATH=$(pwd)
+        CONFIG_FILE_PATH=$(pwd)/settings/*
+        TEMPLATE_GENERATE_PATH=$(pwd)/templates
+        INIT_PATH_CHECK=$(pwd)/.hollaex
+
+    fi
+
+    if [[ "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        CONFIG_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings/*
+        TEMPLATE_GENERATE_PATH=$HOLLAEX_CLI_INIT_PATH/templates
+        INIT_PATH_CHECK=$HOLLAEX_CLI_INIT_PATH/.hollaex
+        
+    fi
+
+    #Quit if necessary flags are missing
+    if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
+
+        printf "\033[91mFailed to detect HollaEx Kit directory! Please re-check your path.\033[39m\n"
+        print_usage;
+        exit 1;
+
+    fi
     
+    for i in ${CONFIG_FILE_PATH[@]}; do
+        source $i
+    done
+
+    source $SCRIPTPATH/tools_generator.sh
+    load_config_variables;
+
+    if [[ "$USE_KUBERNETES" ]]; then
+
+        #Checking Kubernetes dependencies
+        check_kubernetes_dependencies;
+
+        kubectl get deployment --namespace $ENVIRONMENT_EXCHANGE_NAME
+
+    fi
+    
+    if [[ ! "$USE_KUBERNETES" ]]; then
+
+        if [[ -z $(docker ps -a | grep $ENVIRONMENT_EXCHANGE_NAME) ]]; then
+
+            printf "\033[91m\nFailed to detect $ENVIRONMENT_EXCHANGE_NAME on this machine. Please try it again.\033[39m\n"
+
+        else 
+
+            docker ps -a | grep $ENVIRONMENT_EXCHANGE_NAME
+
+        fi
+
+    fi
+
+    printf "\nCalling the exchange health page ($HOLLAEX_CONFIGMAP_API_HOST/v1/health) ...\n"
+
+    if command curl $HOLLAEX_CONFIGMAP_API_HOST/v1/health; then 
+
+        printf "\nSuccessfully reached to the exchange health page.\n"
+
+    else 
+
+        printf "\033[91m\nExchange health page is not responding. Please check the exchange is up.\033[39m\n"
+
+    fi
+
+    exit 0;
+
+elif [[ "$1" == "logs" ]]; then
+
+     while true; do
+        [[ $# -eq 0 ]] && break
+        case $1 in
+            --path)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                HOLLAEX_CLI_INIT_PATH=$1
+                echo "Your HollaEx Kit Path : $HOLLAEX_CLI_INIT_PATH."
+                shift; continue
+                ;;
+            --kube)
+                USE_KUBERNETES=true
+                echo "HollaEx CLI will use your Kubernetes cluster as a target."
+                shift; continue
+                ;;
+            --*) 
+                err_msg "Invalid option: $1"
+                print_usage;
+                exit 1;
+                ;;
+        esac
+        shift
+     done
+
+    if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        HOLLAEX_CLI_INIT_PATH=$(pwd)
+        CONFIG_FILE_PATH=$(pwd)/settings/*
+        TEMPLATE_GENERATE_PATH=$(pwd)/templates
+        INIT_PATH_CHECK=$(pwd)/.hollaex
+
+    fi
+
+    if [[ "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        CONFIG_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings/*
+        TEMPLATE_GENERATE_PATH=$HOLLAEX_CLI_INIT_PATH/templates
+        INIT_PATH_CHECK=$HOLLAEX_CLI_INIT_PATH/.hollaex
+        
+    fi
+
+    #Quit if necessary flags are missing
+    if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
+
+        printf "\033[91mFailed to detect HollaEx Kit directory! Please re-check your path.\033[39m\n"
+        print_usage;
+        exit 1;
+
+    fi
+    
+    for i in ${CONFIG_FILE_PATH[@]}; do
+        source $i
+    done
+
+    source $SCRIPTPATH/tools_generator.sh
+    load_config_variables;
+
+    if [[ "$USE_KUBERNETES" ]]; then
+
+        #Checking Kubernetes dependencies
+        check_kubernetes_dependencies;
+
+        function show_kubernetes_logs_simple() {
+                
+            local POD_ID=$(kubectl get pods --namespace $ENVIRONMENT_EXCHANGE_NAME | grep $ENVIRONMENT_EXCHANGE_NAME | cut -f1 -d " ")
+
+            for i in ${POD_ID[@]}; do
+
+                printf "\nPod : $i\n"
+
+                if [[ $(kubectl logs $i --namespace $ENVIRONMENT_EXCHANGE_NAME --tail 10) ]]; then
+
+                    kubectl logs $i --namespace $ENVIRONMENT_EXCHANGE_NAME --tail 10
+
+                else 
+
+                    echo "There are no logs for Pod : $i."
+
+                fi
+
+                printf "\n"
+
+            done;
+        
+        }
+
+        show_kubernetes_logs_simple;
+
+        printf "\n"
+        echo "Displayed last 10 lines of logs from each pods."
+        echo "To see more detailed logs, Please run 'kubectl logs --namespace $ENVIRONMENT_EXCHANGE_NAME <NAME_OF_POD>'."
+        echo "For example, 'kubectl logs --namespace $ENVIRONMENT_EXCHANGE_NAME myAPIPod>'."
+
+    fi
+    
+    if [[ ! "$USE_KUBERNETES" ]]; then
+
+        if [[ -z $(docker ps -a | grep $ENVIRONMENT_EXCHANGE_NAME) ]]; then
+
+            printf "\033[91m\nFailed to detect $ENVIRONMENT_EXCHANGE_NAME on this machine. Please try it again.\033[39m\n"
+
+        else 
+
+            function show_docker_logs_simple() {
+                
+                local CONTAINER_ID=$(docker ps -a --format "{{.Names}}" | grep $ENVIRONMENT_EXCHANGE_NAME)
+
+                for i in ${CONTAINER_ID[@]}; do
+
+                    printf "\nContainer : $i\n"
+
+                    if [[ $(docker logs $i --tail 10) ]]; then
+
+                        docker logs $i --tail 10
+
+                    else 
+
+                        echo "There are no logs for container : $i."
+
+                    fi
+
+                    printf "\n"
+
+                done;
+            
+            }
+
+            show_docker_logs_simple;
+
+            printf "\n"
+            echo "Displayed last 10 lines of logs from each containers."
+            echo "To see more detailed logs, Please run 'docker logs <NAME_OF_CONTAINER>'."
+            echo "For example, 'docker logs myAPIContainer'."
+
+        fi
+
+    fi
+
+    exit 0;
+ 
+
+elif [[ "$1" == "version" ]]; then
+     
     /bin/cat << EOF
 
 1ttffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffttt.
@@ -3200,9 +3439,10 @@ EOF
 
 else
 
+    printf "\nInvalid Command. Please try it again.\n"
     print_usage;
 
-    exit 0;
+    exit 1;
 
 fi
 
