'hollaex import' now supports json file importation.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -91,6 +91,34 @@ Options:
 EOF
 }
 
+function dev_print_usage() {
+/bin/cat << EOF
+
+# All 'hollaex dev' commands should be run at HollaEx Core directory.
+
+Usage : 
+    hollaex [ dev ] (--flags)
+
+General Flags :
+    --kit-path, Manually pointing HollaEx Kit path. Should be always absolute path.
+    --skip, Run command without user's double confirmation.
+
+Options:
+    --command: Run Docker-Compose commands. (up, down, stop, --build)
+
+    --database_init: Run database initialization scripts.
+
+    --add_coin: Add coin(s) on dev HollaEx environment.
+    
+    --remove_coin: Remove coin(s) on dev HollaEx environment.
+    
+    --add_trading_pair: Add trading pair(s) on dev HollaEx environment.
+
+    --remove_trading_pair: Remove trading pair(s) on dev HollaEx environment.
+
+EOF
+}
+
 if [[ "$1" == "dev" ]]; then
 
     while true; do
@@ -117,6 +145,41 @@ if [[ "$1" == "dev" ]]; then
                 echo "Your docker-compose command : $LOCAL_COMMAND."
                 shift; continue
                 ;;
+            --setup)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                LOCAL_COMMAND="up --build"
+                echo "Your docker-compose command : $LOCAL_COMMAND."
+                shift; continue
+                ;;
+            --start)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                LOCAL_COMMAND="start"
+                echo "Your docker-compose command : $LOCAL_COMMAND."
+                shift; continue
+                ;;
+            --stop)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                LOCAL_COMMAND="stop"
+                echo "Your docker-compose command : $LOCAL_COMMAND."
+                shift; continue
+                ;;
+            --restart)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                LOCAL_COMMAND="restart"
+                echo "Your docker-compose command : $LOCAL_COMMAND."
+                shift; continue
+                ;;
+            --terminate)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                LOCAL_COMMAND="down"
+                echo "Your docker-compose command : $LOCAL_COMMAND."
+                shift; continue
+                ;;
             --database_init)
                 LOCAL_DATABASE_INIT=true
                 echo 'Local database initialization enabled.'
@@ -132,6 +195,26 @@ if [[ "$1" == "dev" ]]; then
                 echo 'Local mocha code test mode enabled.'
                 shift; continue
                 ;;
+            --add_coin)
+                LOCAL_ADD_COIN=true
+                echo 'Adding coin for dev environment.'
+                shift; continue
+                ;;
+            --add_trading_pair)
+                LOCAL_ADD_PAIR=true
+                echo 'Adding trading pair for dev environment.'
+                shift; continue
+                ;;
+            --remove_coin)
+                LOCAL_REMOVE_COIN=true
+                echo 'Removing coin for dev environment.'
+                shift; continue
+                ;;
+            --remove_trading_pair)
+                LOCAL_REMOVE_PAIR=true
+                echo 'Removing trading pair for dev environment.'
+                shift; continue
+                ;;
             --skip)
                 RUN_WITH_VERIFY=false
                 echo 'Skipping the command confirmation.'
@@ -139,7 +222,7 @@ if [[ "$1" == "dev" ]]; then
                 ;;
             --*) 
                 err_msg "Invalid option: $1"
-                print_usage;
+                dev_print_usage;
                 exit 1;
                 ;;
         esac
@@ -172,6 +255,43 @@ if [[ "$1" == "dev" ]]; then
     
     source $SCRIPTPATH/tools_generator.sh
     load_config_variables;
+
+    # ADD & REMOVE COINS AND PAIRS INTERATION FOR DEV
+    if [[ "$LOCAL_ADD_COIN" ]]; then    
+
+        add_coin_input
+
+        add_coin_exec
+
+        exit 0;
+
+    elif [[ "$LOCAL_REMOVE_COIN" ]]; then
+
+        remove_coin_input
+
+        remove_coin_exec
+
+        exit 0;
+
+
+    elif [[ "$LOCAL_ADD_PAIR" ]]; then
+
+        add_pair_input
+
+        add_pair_exec
+
+        exit 0;
+
+
+    elif [[ "$LOCAL_REMOVE_PAIR" ]]; then
+
+        remove_pair_input
+
+        remove_pair_exec
+
+        exit 0;
+
+    fi
 
     if [[ ! "$USE_KUBERNETES" ]]; then
 
@@ -871,29 +991,25 @@ elif [[ "$1" == "setup" ]]; then
 
 elif [[ "$1" == "import" ]]; then
 
-    # while true; do
-    #     [[ $# -eq 0 ]] && break
-    #     case $1 in
-    #         --file)
-    #             shift 
-    #             case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
-    #             HOLLAEX_IMPORT_PATH=$1
-    #             echo "Your file / directory path to import : $HOLLAEX_IMPORT_PATH."
-    #             if [[ "$2" ]]; then
-    #                 echo "Your second file / directory path to import : $HOLLAEX_IMPORT_PATH_2."
-    #             fi
-    #             shift; continue
-    #             ;;
-    #         --*) 
-    #             err_msg "Invalid option: $1"
-    #             print_usage;
-    #             exit 1;
-    #             ;;
-    #     esac
-    #     shift
-    # done
+    while true; do
+        [[ $# -eq 0 ]] && break
+        case $1 in
+            --path)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                HOLLAEX_IMPORT_PATH_INPUT=$@
+                shift; continue
+                ;;
+            --*) 
+                err_msg "Invalid option: $1"
+                print_usage;
+                exit 1;
+                ;;
+        esac
+        shift
+    done
 
-    HOLLAEX_IMPORT_PATH_INPUT=$@
+    # HOLLAEX_IMPORT_PATH_INPUT=$@
     IFS=' ' read -ra HOLLAEX_IMPORT_PATH <<< "$HOLLAEX_IMPORT_PATH_INPUT"    #Convert string to array
 
     if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
@@ -915,8 +1031,6 @@ elif [[ "$1" == "import" ]]; then
         
     fi
     
-
-
     #Quit if necessary flags are missing
     if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
 
@@ -947,54 +1061,121 @@ OLD_PAIRS=$(echo $HOLLAEX_CONFIGMAP_PAIRS)
 
 EOL
 
-    rm $CONFIG_FILE_PATH
+    if [[ "${HOLLAEX_IMPORT_PATH[@]}" == *"json"* ]]; then
 
-    for i in ${HOLLAEX_IMPORT_PATH[@]}; do
+         # Returns error If 'jq' doesn't exists.
+        if ! command jq --version > /dev/null 2>&1; then
 
-        if [[ -d "$i" ]]; then
-            
-            if command cp $i/* $IMPORT_FILE_PATH; then
+            printf "\033[91mError: 'jq' (https://stedolan.github.io/jq/) has not been detected on your system.\033[39m\n"
+            echo "HollaEx CLI requires 'jq' to handle certain functionalities."
+            echo "Please install it first and try again."
 
-                IS_IMPORT_SUCCESS=true
-            
-            else 
+            printf "\nFor Ubuntu (Debian) users: 'apt-get install -y jq'\n"
+            printf "For macOS users with Homebrew: 'brew install jq'\n\n"
 
-                IS_IMPORT_SUCCESS=false
+            exit 1;
+
+        fi
+
+        echo "Converting imported file to HollaEx CLI settings file format..."
+
+        for i in ${CONFIG_FILE_PATH[@]}; do
+
+        if command grep -q "HOLLAEX_CONFIGMAP_API_NAME=" $i > /dev/null ; then
+
+            export CONFIGMAP_FILE_PATH=$i
+
+        fi
+
+        done
+
+        for i in ${CONFIG_FILE_PATH[@]}; do
+
+            if command grep -q "HOLLAEX_SECRET_ACTIVATION_CODE=" $i > /dev/null ; then
+
+                export SECRET_FILE_PATH=$i
+
+            fi
+
+        done
+        
+        BITHOLLA_USER_EXCHANGE_LIST=$(cat $HOLLAEX_IMPORT_PATH)
+
+        # SAVING USER ACTIVATION CODE.
+        export EXCHANGE_USER_ACTIVATION_CODE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[0].activation_code";);
+        sed -i.bak "s/HOLLAEX_SECRET_ACTIVATION_CODE=.*/HOLLAEX_SECRET_ACTIVATION_CODE=${EXCHANGE_USER_ACTIVATION_CODE}/" $SECRET_FILE_PATH;
+        rm $SECRET_FILE_PATH.bak
+
+        BITHOLLA_USER_EXCHANGE_ORDER=0
+
+        hollaex_pull_and_apply_exchange_data;
+
+        apply_coins_config_to_settings_file;
+
+        apply_pairs_config_to_settings_file;
+
+        if command grep -q "ENVIRONMENT_ADD_COIN_${COIN_PREFIX}_COIN" $CONFIGMAP_FILE_PATH > /dev/null && command grep -q "ENVIRONMENT_ADD_PAIR_${PAIR_PREFIX}" $CONFIGMAP_FILE_PATH > /dev/null; then
+
+            IS_IMPORT_SUCCESS=true
+
+        else 
+
+            IS_IMPORT_SUCCESS=false
+
+        fi
+
+    else 
+
+        rm $CONFIG_FILE_PATH
+
+        for i in ${HOLLAEX_IMPORT_PATH[@]}; do
+
+            if [[ -d "$i" ]]; then
+                
+                if command cp $i/* $IMPORT_FILE_PATH; then
+
+                    IS_IMPORT_SUCCESS=true
+                
+                else 
+
+                    IS_IMPORT_SUCCESS=false
+                
+                fi
+
+            elif [[ -f "$i" ]]; then
+
+                if command cp $i $IMPORT_FILE_PATH; then
+
+                    IS_IMPORT_SUCCESS=true
+                
+                else 
+
+                    IS_IMPORT_SUCCESS=false
+                
+                fi
             
             fi
 
-        elif [[ -f "$i" ]]; then
+        done;
 
-            if command cp $i $IMPORT_FILE_PATH; then
+        if [[ -d "$HOLLAEX_IMPORT_PATH" ]]; then
+            
+            if command cp $HOLLAEX_IMPORT_PATH/* $IMPORT_FILE_PATH; then
 
                 IS_IMPORT_SUCCESS=true
             
-            else 
+            fi
 
-                IS_IMPORT_SUCCESS=false
+        elif [[ -f "$HOLLAEX_IMPORT_PATH" ]]; then
+
+            if command cp $HOLLAEX_IMPORT_PATH $IMPORT_FILE_PATH; then
+
+                IS_IMPORT_SUCCESS=true
             
             fi
         
         fi
 
-    done;
-
-    if [[ -d "$HOLLAEX_IMPORT_PATH" ]]; then
-        
-        if command cp $HOLLAEX_IMPORT_PATH/* $IMPORT_FILE_PATH; then
-
-            IS_IMPORT_SUCCESS=true
-        
-        fi
-
-    elif [[ -f "$HOLLAEX_IMPORT_PATH" ]]; then
-
-        if command cp $HOLLAEX_IMPORT_PATH $IMPORT_FILE_PATH; then
-
-            IS_IMPORT_SUCCESS=true
-        
-        fi
-    
     fi
 
     if [[ "$IS_IMPORT_SUCCESS" == true ]]; then 
@@ -1513,92 +1694,9 @@ elif [[ "$1" == "pull" ]]; then
 
     hollaex_pull_and_apply_exchange_data;
 
-    # Applying coin (asset) configs to settings file.
+    apply_coins_config_to_settings_file;
 
-    BITHOLLA_USER_EXCHANGE_ASSETS_COUNT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS" | jq '.| length ')
-    BITHOLLA_USER_EXCHANGE_ASSETS_COUNT=$(($BITHOLLA_USER_EXCHANGE_ASSETS_COUNT-1))
-
-    for ((i=0;i<=BITHOLLA_USER_EXCHANGE_ASSETS_COUNT;i++)); do
-
-        export COIN_SYMBOL=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_SYMBOL") 
-        export COIN_FULLNAME=\'$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_NAME")\'
-
-        export COIN_ALLOW_DEPOSIT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_ALLOW_DEPOSITS")
-
-        if [[ "$COIN_ALLOW_DEPOSIT" == "Y" ]]; then
-            export COIN_ALLOW_DEPOSIT="true"
-        elif [[ "$COIN_ALLOW_DEPOSIT" == "N" ]]; then
-            export COIN_ALLOW_DEPOSIT="false"
-        fi
-
-        export COIN_ALLOW_WITHDRAWAL=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_ALLOW_WITHDRAWAL")
-        
-        if [[ "$COIN_ALLOW_WITHDRAWAL" == "Y" ]]; then
-            export COIN_ALLOW_WITHDRAWAL="true"
-        elif [[ "$COIN_ALLOW_WITHDRAWAL" == "N" ]]; then
-            export COIN_ALLOW_WITHDRAWAL="false"
-        fi
-
-        export COIN_WITHDRAWAL_FEE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_WITHDRAWAL_FEE")
-        export COIN_MIN=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_MINIMUM_WITHDRAWAL")
-        export COIN_MAX=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_MAXIMUM_WITHDRAWAL")
-        export COIN_INCREMENT_UNIT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_INCREMENT_AMOUNT")
-        export COIN_DEPOSIT_LIMITS_PARSED=\'$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].deposit" | tr -d '\n')\'
-        export COIN_WITHDRAWAL_LIMITS_PARSED=\'$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].deposit" | tr -d '\n')\'
-
-        export COIN_ACTIVE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.ASSETS[$i].ASSET_ACTIVATE")
-
-        if [[ "$COIN_ACTIVE" == "Y" ]]; then
-            export COIN_ACTIVE="true"
-        elif [[ "$COIN_ACTIVE" == "N" ]]; then
-            export COIN_ACTIVE="false"
-        fi
-
-        export COIN_PREFIX=$(echo ${COIN_SYMBOL} | tr a-z A-Z)
-
-        remove_existing_coin_configs_from_settings;
-
-        save_coin_configs;
-
-    done;
-
-    # Applying pair (pairs) configs to settings file.
-    BITHOLLA_USER_EXCHANGE_PAIRS_COUNT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS" | jq '.| length ')
-    BITHOLLA_USER_EXCHANGE_PAIRS_COUNT=$(($BITHOLLA_USER_EXCHANGE_PAIRS_COUNT-1))
-
-    for ((i=0;i<=BITHOLLA_USER_EXCHANGE_PAIRS_COUNT;i++)); do
-
-        export PAIR_BASE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].BASE_ASSET")
-        export PAIR_2=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].PRICED_ASSET")
-        export TAKER_FEES_PARSED=\'$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].TAKER_FEE" | tr -d '\n')\'
-        export MAKER_FEES_PARSED=\'$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].MAKER_FEE" | tr -d '\n')\'
-        export MIN_SIZE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].MINIMUM_TRADABLE_AMOUNT")
-        export MAX_SIZE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].MAXIMUM_TRADABLE_AMOUNT")
-        export MIN_PRICE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].MINIMUM_TRADABLE_PRICE")
-        export MAX_PRICE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].MAXIMUM_TRADABLE_PRICE")
-        export INCREMENT_SIZE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].INCREMENT_AMOUNT")
-        export INCREMENT_PRICE=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].INCREMENT_PRICE")
-
-        if [[ "$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].info.biz.PAIRS[$i].PAIR_ACTIVATE")" == "Y" ]]; then
-
-            export PAIR_ACTIVE_BOOL=true
-        
-        else 
-
-            export PAIR_ACTIVE_BOOL=false
-        
-        fi 
-
-        export PAIR_ACTIVE=${PAIR_ACTIVE_BOOL}
-        export PAIR_NAME=$(echo "${PAIR_BASE}-${PAIR_2}") 
-
-        export PAIR_PREFIX="$(echo $PAIR_BASE | tr a-z A-Z)_$(echo $PAIR_2 | tr a-z A-Z)"
-
-        remove_existing_pairs_configs_from_settings;
-
-        save_pairs_configs;
-
-    done;
+    apply_pairs_config_to_settings_file;
 
     if command grep -q "ENVIRONMENT_ADD_COIN_${COIN_PREFIX}_COIN" $CONFIGMAP_FILE_PATH > /dev/null && command grep -q "ENVIRONMENT_ADD_PAIR_${PAIR_PREFIX}" $CONFIGMAP_FILE_PATH > /dev/null; then
 
