"hollaex dash" command sets for dash login and logout, "hollaex init" for kit independent exchange initialzation.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -45,14 +45,14 @@ function print_usage() {
 /bin/cat << EOF
 
 Usage : 
-    hollaex [ dev ] [ server ] [ import ] [ export ] [ login ] [ pull ] [ logout ] [ build ] [ web ] [ toolbox ] [ status ] [ logs ] [ version ] (--flags)
+    hollaex [ server ] [ web ] [ init ] [ prod ] [ import ] [ export ] [ dash ] [ pull ] [ build ] [ dev ] [ toolbox ] [ status ] [ logs ] [ version ] (--flags)
 
 General Flags (Except for 'hollaex init', 'hollaex import'):
     --path, Manually pointing HollaEx Kit path. Should be always absolute path.
     --kube, Set HollaEx CLI to target Kubernetes. Make sure to setup your local kubectl before using it.
     --skip, Run command without user's double confirmation.
 
-Options:
+Options:    
     import: Import settings files generated by using bitHolla Dashboard (dash.bitholla.com).
         --path, Path of file or directory where settings files are stored.
         --with_aws_s3 <BUCKET_NAME>, Import settings files from the remote AWS S3 bucket.
@@ -61,11 +61,13 @@ Options:
         --path, Path of the directory to export settings files.
         --with_aws_s3 <BUCKET_NAME>, Export settings files to the remote AWS S3 bucket.
     
-    login: Log in with bitHolla Dashboard account and select my Activation code. 
+    dash: Interaction with bitHolla Dashboard.
+        --login: Log in with bitHolla Dashboard account.
+        --logout Log out and remove my bound account.
+
+    init: Initialize the HollaEx Kit by setting up the target network, sign up as an admin, and claim a new exchange name.
 
     pull: Pull the exchange data from the bitHolla Dashboard.
-
-    logout: Log out and remove my bound Activation code on local.
 
     prod: Bring up the exchange to production. Including public domain setup and SSL configuraiton.
 
@@ -458,6 +460,80 @@ if [[ "$1" == "dev" ]]; then
 
     exit 0;
 
+elif [[ "$1" == "init" ]]; then
+
+    printf "\n\033[1mSelect the network\033[0m\n\n"
+
+    echo -e "Before you continue, You need to \033[1mselect the network\033[0m that you want to use with the exchange."
+    echo -e "HollaEx Kit will be connected to the official HollaEx Network (\033[1mapi.hollaex.network\033[0m) by default." 
+    echo -e "If you want to connect to a different one, please type in an API URL for the custom network.\n"
+    echo -e "Do you want to want to continue with the official HollaEx Network? (Y/n)\n"
+    read answer
+
+    # If user selected a custom network option
+    if [[ ! "$answer" = "${answer#[Nn]}" ]]; then
+
+        echo "***************************************************************"
+        printf "\nPlease type the URL of your custom network. (Example: api.hollaex.network)\n"
+        read hollaexAPIURL
+
+        while true;
+            do if [[ ! "$hollaexAPIURL" == *"."* ]]; then
+                printf "\nPlease confirm that you typed in a correct url.\n"
+                echo  "Custom Network API URL: "
+                read hollaexAPIURL
+            else
+                break;
+            fi
+        done
+        
+    fi
+
+    printf "\n"
+    echo "${hollaexAPIURL:-api.hollaex.network} ✔"
+    printf "\n"
+
+    ###
+    HollaEx Network Sign Up Part
+    TBA
+    ###
+
+    printf "\n\033[1mNew exchange name\033[0m\n\n"
+
+    echo -e "The last part here. Please type in the name of your new exchange you going to run."
+    printf "\033[2m- Alphanumeric, Dash (-), Underscore Only (_). No space or special character allowed.\033[22m\n" 
+    read hollaexExchangeName
+
+    while true;
+        do if [[ ! "$hollaexExchangeName" =~ ^[A-Za-z0-9_-]+$ ]] && [[ "$IS_AVAILABLE_hollaexExchangeName" ]]; then 
+            printf "\nInvalid Exchange Name. Make sure to input Alphanumeric, Dash (-), Underscore Only (_).\n"
+            echo "New Exchange Name: "
+            read hollaexExchangeName
+        else
+            echo "Checking on the network that the name you provided is available..."
+            if ! command CURL SOMETHING; then 
+
+                IS_AVAILABLE_hollaexExchangeName=false
+                echo "Sorry, But the name is already occupied!"
+            
+            fi
+            break;
+        fi
+    done
+
+    printf "\n"
+    echo "$hollaexExchangeName ✔"
+    printf "\n"
+
+    # Update settings files with provided values
+    for i in ${CONFIG_FILE_PATH[@]}; do
+        if command grep -q "ENVIRONMENT_EXCHANGE_NAME" $i > /dev/null ; then
+            CONFIGMAP_FILE_PATH=$i
+            sed -i.bak "s/ENVIRONMENT_EXCHANGE_NAME=.*/ENVIRONMENT_EXCHANGE_NAME=$hollaexExchangeName/" $CONFIGMAP_FILE_PATH
+            sed -i.bak "s/HOLLAEX_CONFIGMAP_NETWORK_URL=.*/HOLLAEX_CONFIGMAP_NETWORK_URL=$hollaexAPIURL/" $CONFIGMAP_FILE_PATH
+            rm $CONFIGMAP_FILE_PATH.bak
+        fi
+    done
 
 elif [[ "$1" == "server" ]]; then
     while true; do
@@ -1231,6 +1307,28 @@ elif [[ "$1" == "export" ]]; then
     fi 
 
     printf "\033[92mYour settings files has been exported successfully!\033[39m\n"
+
+elif [[ "$1" == "dash" ]]; then
+
+    while true; do
+        [[ $# -eq 0 ]] && break
+        case $1 in
+            --login)
+                hollaex login ${@:2}
+                break
+                ;;
+            --logout)
+                hollaex logout ${@:2}
+                break
+                ;;
+            --*) 
+                err_msg "Invalid option: $1"
+                print_usage;
+                exit 1;
+                ;;
+        esac
+        shift
+    done
 
 elif [[ "$1" == "login" ]]; then
 
