Multiarch support improvement

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -616,16 +616,31 @@ elif [[ "$1" == "setup" ]]; then
         source $i
     done;
 
-    # Building the image
-    if [[ "$USE_KUBERNETES" ]]; then
+    if [[ "$ENVIORNMENT_HOLLAEX_CPU_ARCH" ]]; then 
 
-        hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --kube --is_hollaex_setup
+        if [[ "$USE_KUBERNETES" ]]; then
+
+            hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --kube --is_hollaex_setup --arch $ENVIORNMENT_HOLLAEX_CPU_ARCH
+
+        else 
+
+            hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --is_hollaex_setup --arch $ENVIORNMENT_HOLLAEX_CPU_ARCH
+
+        fi
 
     else 
 
-        hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --is_hollaex_setup
+        if [[ "$USE_KUBERNETES" ]]; then
 
-    fi 
+            hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --kube --is_hollaex_setup 
+
+        else 
+
+            hollaex build --registry ${ENVIRONMENT_DOCKER_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY} --is_hollaex_setup 
+
+        fi
+
+    fi
 
     for i in ${CONFIG_FILE_PATH[@]}; do
         source $i
@@ -3135,7 +3150,7 @@ elif [[ "$1" == "build" ]]; then
     for i in ${CONFIG_FILE_PATH[@]}; do
         source $i
     done;
-    
+
     source $SCRIPTPATH/tools_generator.sh
     load_config_variables;
 
@@ -3144,7 +3159,13 @@ elif [[ "$1" == "build" ]]; then
     if [[ "$ENVIORNMENT_HOLLAEX_CPU_ARCH" ]]; then 
 
         export ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE="$(cat $HOLLAEX_CLI_INIT_PATH/server/package.json | jq -r '.version')-${ENVIORNMENT_HOLLAEX_CPU_ARCH}"
-    
+
+        ENVIRONMENT_NODE_VERSION=$(cat $HOLLAEX_CLI_INIT_PATH/Dockerfile | grep -e "FROM.*node:" | cut -f2 -d ":")
+
+        # Overriding the base image with the env value
+        sed -i.bak "s/FROM .*node.*/FROM ${ENVIORNMENT_HOLLAEX_CPU_ARCH}\/node:${ENVIRONMENT_NODE_VERSION}/" $HOLLAEX_CLI_INIT_PATH/Dockerfile
+        rm $HOLLAEX_CLI_INIT_PATH/Dockerfile.bak
+
     else 
 
         export ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE="$(cat $HOLLAEX_CLI_INIT_PATH/server/package.json | jq -r '.version')"
@@ -3354,6 +3375,20 @@ elif [[ "$1" == "upgrade" ]]; then
                 echo "HollaEx CLI will ignore local settings update on restart."
                 shift; continue
                 ;;
+            --arch)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                if [[ "$1" == "amd64" ]] || [[ "$1" == "arm64v8" ]] || [[ "$1" == "s390x" ]]; then
+                    export ENVIORNMENT_HOLLAEX_CPU_ARCH=$1
+                    echo "Target CPU Arch: $ENVIORNMENT_HOLLAEX_CPU_ARCH."
+                else 
+                    echo -e "\n\033[91mError: Not supported CPU arch!\033[39m"
+                    echo "Supported Arches: amd64, arm64v8, s390x."
+                    echo -e "Please try it again with the supported arch name.\n"
+                    exit 1;
+                fi
+                shift; continue
+                ;;
             --skip)
                 RUN_WITH_VERIFY=false
                 echo "Skipping the command confirmation."
@@ -3434,10 +3469,21 @@ elif [[ "$1" == "upgrade" ]]; then
     fi
 
     #hollaex build
+
+    export ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY=${ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY_OVERRIDE:-$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY}
     
     # Update the Core version to the user specified version, or use a latest compatible one.
-    export ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE="$(cat $HOLLAEX_CLI_INIT_PATH/server/package.json | jq -r '.version')"
-    export ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-core-${ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE}-$(date +%y%m%d%H%M)"
+    if [[ "$ENVIORNMENT_HOLLAEX_CPU_ARCH" ]]; then 
+
+        export ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE="$(cat $HOLLAEX_CLI_INIT_PATH/server/package.json | jq -r '.version')-${ENVIORNMENT_HOLLAEX_CPU_ARCH}"
+    
+    else 
+
+        export ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE="$(cat $HOLLAEX_CLI_INIT_PATH/server/package.json | jq -r '.version')"
+
+    fi     
+
+    export ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-server-${ENVIRONMENT_DOCKER_IMAGE_VERSION_OVERRIDE}-$(date +%y%m%d%H%M)"
     
     export ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION_OVERRIDE=$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION
 
@@ -3801,6 +3847,20 @@ elif [[ "$1" == "web" ]]; then
                 echo "Target Replicas: $HOLLAEX_WEB_SCALE_TARGET_REPLICAS."
                 shift; continue
                 ;;
+            --arch)
+                shift 
+                case $1 in (-*|"") err_msg_l; print_usage; exit 1; esac
+                if [[ "$1" == "amd64" ]] || [[ "$1" == "arm64v8" ]] || [[ "$1" == "s390x" ]]; then
+                    export ENVIORNMENT_HOLLAEX_CPU_ARCH=$1
+                    echo "Target CPU Arch: $ENVIORNMENT_HOLLAEX_CPU_ARCH."
+                else 
+                    echo -e "\n\033[91mError: Not supported CPU arch!\033[39m"
+                    echo "Supported Arches: amd64, arm64v8, s390x."
+                    echo -e "Please try it again with the supported arch name.\n"
+                    exit 1;
+                fi
+                shift; continue
+                ;;
             --*) 
                 err_msg "Invalid option: $1"
                 print_usage;
@@ -3869,6 +3929,19 @@ elif [[ "$1" == "web" ]]; then
 
     fi
 
+    if [[ "$ENVIORNMENT_HOLLAEX_CPU_ARCH" ]]; then 
+
+        ENVIRONMENT_WEB_NODE_VERSION=$(cat $HOLLAEX_CLI_INIT_PATH/web/docker/Dockerfile | grep "FROM.*node:" | cut -f2 -d ":")
+        ENVIRONMENT_WEB_NGINX_VERSION=$(cat $HOLLAEX_CLI_INIT_PATH/web/docker/Dockerfile | grep "FROM.*nginx:" | cut -f2 -d ":")
+
+        # Overriding the base image with the env value
+        sed -i.bak "s/FROM .*node.*/FROM ${ENVIORNMENT_HOLLAEX_CPU_ARCH}\/node:${ENVIRONMENT_WEB_NODE_VERSION}/" $HOLLAEX_CLI_INIT_PATH/web/docker/Dockerfile
+        sed -i.bak "s/FROM .*nginx.*/FROM ${ENVIORNMENT_HOLLAEX_CPU_ARCH}\/nginx:${ENVIRONMENT_WEB_NGINX_VERSION}/" $HOLLAEX_CLI_INIT_PATH/web/docker/Dockerfile
+
+        rm $HOLLAEX_CLI_INIT_PATH/web/docker/Dockerfile.bak
+
+    fi
+
     # hollaex web --setup
     if [[ "$WEB_CLIENT_SETUP" ]]; then
 
@@ -3880,7 +3953,7 @@ elif [[ "$1" == "web" ]]; then
         
         fi 
 
-        export ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-web-$(cat version)-$(date +%y%m%d%H%M)"
+        export ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-web-$(cat $HOLLAEX_CLI_INIT_PATH/web/package.json | jq -r '.version')-$(date +%y%m%d%H%M)"
         build_user_hollaex_web;
 
         if [[ "$USE_KUBERNETES" ]]; then
@@ -4524,7 +4597,7 @@ elif [[ "$1" == "web" ]]; then
 
     if [[ "$WEB_CLIENT_REBUILD" ]];  then
         
-        export ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-web-$(cat version)-$(date +%y%m%d%H%M)"
+        export ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_VERSION="${ENVIRONMENT_EXCHANGE_NAME}-web-$(cat $HOLLAEX_CLI_INIT_PATH/web/package.json | jq -r '.version')-$(date +%y%m%d%H%M)"
         build_user_hollaex_web;
 
         echo -e "\nPlease run 'hollaex web --apply --registry $ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_REGISTRY --tag $ENVIRONMENT_USER_HOLLAEX_WEB_IMAGE_VERSION $(if [[ "$USE_KUBERNETES" ]]; then echo "--kube"; fi)' to apply it on the server."
