Avoid running hollaex setup again if the exchange is already set.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -1674,6 +1674,18 @@ elif [[ "$1" == "pull" ]]; then
 
     fi
 
+    if [[ $(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$BITHOLLA_USER_EXCHANGE_ORDER].is_setup") == true ]]; then
+
+        printf "\n\033[91mError: Your exchange has been already setup!\033[39m\n"
+        printf "You can't run 'hollaex setup' multiple times for the same exchange.\n\n"
+        printf "Please create a new exchange at https://dash.bitholla.com, and try it again.\n\n"
+
+        printf "If you fully understand what you are doing, you can use 'hollaex setup --force' flag to run a force setup.\n"
+
+        exit 1;
+
+    fi
+
     hollaex_pull_and_apply_exchange_data;
 
     for i in ${CONFIG_FILE_PATH[@]}; do
