1.8.0 skeleton with 'hollaex login' and 'hollaex logout' support.

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -35,6 +35,14 @@ Options:
     
     import: Import settings files generated by using bitHolla Dashboard (dash.bitholla.com).
         --file, Path of file or directory where settings files are stored.
+    
+    login: Log in with bitHolla Dashboard account and select my Activation code. 
+
+    logout: Log out and remove my bound Activation code on local.
+
+    pull: Pull my Exchange configurations from bitHolla Dashboard to local.
+
+    push: Push my local Exchange configurations to bitHolla Dashboard.
 
     start: Start the exchange which already been configured by 'hollaex setup' command.
 
@@ -920,6 +928,238 @@ EOL
 
         exit 1;
     
+    fi
+
+elif [[ "$1" == "login" ]]; then
+
+    if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        HOLLAEX_CLI_INIT_PATH=$(pwd)
+        CONFIG_FILE_PATH=$(pwd)/settings/*
+        IMPORT_FILE_PATH=$(pwd)/settings
+        TEMPLATE_GENERATE_PATH=$(pwd)/templates
+        INIT_PATH_CHECK=$(pwd)/.hollaex
+
+    fi
+
+    if [[ "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        CONFIG_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings/*
+        IMPORT_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings
+        TEMPLATE_GENERATE_PATH=$HOLLAEX_CLI_INIT_PATH/templates
+        INIT_PATH_CHECK=$HOLLAEX_CLI_INIT_PATH/.hollaex
+        
+    fi
+
+    #Quit if necessary flags are missing
+    if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
+
+        printf "\033[91mFailed to detect HollaEx Kit directory! Please re-check your path.\033[39m\n"
+        print_usage;
+        exit 1;
+
+    fi
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+
+        if command grep -q "HOLLAEX_CONFIGMAP_API_NAME=" $i > /dev/null ; then
+
+            export CONFIGMAP_FILE_PATH=$i
+
+        fi
+
+    done
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+
+        if command grep -q "HOLLAEX_SECRET_ACTIVATION_CODE=" $i > /dev/null ; then
+
+            export SECRET_FILE_PATH=$i
+
+        fi
+
+    done
+
+
+    echo "bitHolla Account Email: "
+    read email
+
+    echo "bitHolla Account Password: "
+    read -s password
+    printf "\n"
+
+    echo "OTP Code (If required. Leave it as blank if it's not.): "
+    read otp
+
+    BITHOLLA_ACCOUNT_TOKEN=$(curl -s -H "Content-Type: application/json" \
+        --request POST \
+        --data "{\"email\": \"${email}\", \"password\": \"${password}\", \"otp_code\": \"${otp}\", \"service\": \"cli\"}" \
+        https://api.bitholla.com/v1/login \
+        | jq -r '.token')
+
+    if [[ ! "$BITHOLLA_ACCOUNT_TOKEN" ]] || [[ "$BITHOLLA_ACCOUNT_TOKEN" == "null" ]]; then
+
+        printf "\033[91mFailed to authenticate on bitHolla Server with your passed credentials.\033[39m\n"
+        echo -e "Please try it again.\n"
+        exit 1;
+
+    else 
+
+        printf "\n\033[92mSuccessfully authenticated on bitHolla Server.\033[39m\n"
+        echo "Info: Your authentication will be only available for 24 hours."
+
+    fi
+
+    BITHOLLA_USER_EXCHANGE_LIST=$(curl -s -H "Content-Type: application/json" -H "Authorization: Bearer $BITHOLLA_ACCOUNT_TOKEN"\
+        --request GET \
+        https://api.bitholla.com/v1/exchange \
+       | jq '.')
+    
+    BITHOLLA_USER_EXCHANGE_COUNT=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r '.count')
+
+    # Subtracting 1 from total count due to the array starts from 0, not from 1.
+    BITHOLLA_USER_EXCHANGE_COUNT=$((BITHOLLA_USER_EXCHANGE_COUNT-1))
+
+    echo -e "\n"
+
+    for ((i=0;i<=BITHOLLA_USER_EXCHANGE_COUNT;i++)); do 
+
+        echo "Exchange number : $i";
+
+        echo "Name:" $(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$i].name");
+        echo "Activation Code:" $(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$i].activation_code");
+        echo -e "\n"
+
+        EXCHANGE_NAME_TEMP=EXCHANGE_NAME_${i}
+        EXCHANGE_ACTIVATION_CODE_TEMP=EXCHANGE_ACTIVATION_CODE_${i}
+
+        export $(echo $EXCHANGE_NAME_TEMP)=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$i].name";);
+        export $(echo $EXCHANGE_ACTIVATION_CODE_TEMP)=$(echo $BITHOLLA_USER_EXCHANGE_LIST | jq -r ".data[$i].activation_code";);
+
+    done;
+
+    echo "Please pick up the exchange number you want to bind."
+    read answer
+    
+    printf "\n"
+    SELECTED_EXCHANGE_NAME=EXCHANGE_NAME_${answer}
+    SELECTED_EXCHANGE_ACTIVATION_CODE=EXCHANGE_ACTIVATION_CODE_${answer}
+
+    echo "Selected Exchange name: ${!SELECTED_EXCHANGE_NAME}"
+    echo "Selected Activation code: ${!SELECTED_EXCHANGE_ACTIVATION_CODE}"
+
+    if command sed -i.bak "s/HOLLAEX_CONFIGMAP_API_NAME=.*/HOLLAEX_CONFIGMAP_API_NAME=${!SELECTED_EXCHANGE_NAME}/" $CONFIGMAP_FILE_PATH; then
+
+        rm $CONFIGMAP_FILE_PATH.bak
+
+        if command sed -i.bak "s/HOLLAEX_SECRET_ACTIVATION_CODE=.*/HOLLAEX_SECRET_ACTIVATION_CODE=${!SELECTED_EXCHANGE_ACTIVATION_CODE}/" $SECRET_FILE_PATH; then
+
+            rm $SECRET_FILE_PATH.bak
+
+            printf "\n\033[92mSuccessfully bound the selected exchange to HollaEx Kit.\033[39m\n"
+        fi
+    
+    else
+
+        printf "\033[91mFailed to bind selected exchange to HollaEx Kit.\033[39m\n"
+        echo "Please review the error and try again."
+        exit 1;
+
+    fi
+
+elif [[ "$1" == "logout" ]]; then
+
+    if [[ ! "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        HOLLAEX_CLI_INIT_PATH=$(pwd)
+        CONFIG_FILE_PATH=$(pwd)/settings/*
+        IMPORT_FILE_PATH=$(pwd)/settings
+        TEMPLATE_GENERATE_PATH=$(pwd)/templates
+        INIT_PATH_CHECK=$(pwd)/.hollaex
+
+    fi
+
+    if [[ "$HOLLAEX_CLI_INIT_PATH" ]]; then
+
+        CONFIG_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings/*
+        IMPORT_FILE_PATH=$HOLLAEX_CLI_INIT_PATH/settings
+        TEMPLATE_GENERATE_PATH=$HOLLAEX_CLI_INIT_PATH/templates
+        INIT_PATH_CHECK=$HOLLAEX_CLI_INIT_PATH/.hollaex
+        
+    fi
+
+    #Quit if necessary flags are missing
+    if [[ ! "$CONFIG_FILE_PATH" ]] || [[ ! -f "$INIT_PATH_CHECK" ]]; then
+
+        printf "\033[91mFailed to detect HollaEx Kit directory! Please re-check your path.\033[39m\n"
+        print_usage;
+        exit 1;
+
+    fi
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+
+        if command grep -q "HOLLAEX_CONFIGMAP_API_NAME=" $i > /dev/null ; then
+
+            export CONFIGMAP_FILE_PATH=$i
+
+        fi
+
+    done
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+
+        if command grep -q "HOLLAEX_SECRET_ACTIVATION_CODE=" $i > /dev/null ; then
+
+            export SECRET_FILE_PATH=$i
+
+        fi
+
+    done
+
+    for i in ${CONFIG_FILE_PATH[@]}; do
+        source $i
+    done;
+
+    source $SCRIPTPATH/tools_generator.sh
+    load_config_variables;
+
+    if [[ ! "$HOLLAEX_CONFIGMAP_API_NAME" ]] || [[ ! "$HOLLAEX_SECRET_ACTIVATION_CODE" ]]; then
+
+        printf "\033[91mFailed to read pre-bound Exchange name or Activation code.\033[39m\n"
+        echo "'hollaex logout' works only after you successfully logged in."
+        exit 1;
+    
+    fi
+
+    printf "\nCurrent bound Exchange name: \033[92m$HOLLAEX_CONFIGMAP_API_NAME\033[39m\n\n"
+    echo "This command will remove both Exchange name and Activation code from your local HollaEx Kit."
+    echo "The rest of Exchagne configurations WILL NOT BE removed."
+    echo "Are you sure you want to unbind this exchange from HollaEx Kit? (y/N)"
+    read answer
+
+    if [[ "$answer" = "${answer#[Yy]}" ]]; then
+        echo "Exiting..."
+        exit 0;
+    fi
+
+    if command sed -i.bak "s/HOLLAEX_CONFIGMAP_API_NAME=.*/HOLLAEX_CONFIGMAP_API_NAME=/" $CONFIGMAP_FILE_PATH; then
+
+        rm $CONFIGMAP_FILE_PATH.bak
+
+        if command sed -i.bak "s/HOLLAEX_SECRET_ACTIVATION_CODE=.*/HOLLAEX_SECRET_ACTIVATION_CODE=/" $SECRET_FILE_PATH; then
+
+            rm $SECRET_FILE_PATH.bak
+
+            printf "\n\033[92mSuccessfully removed the exchange data from HollaEx Kit.\033[39m\n"
+        fi
+    
+    else
+
+        printf "\033[91mFailed to remove exchange data from HollaEx Kit.\033[39m\n"
+        echo "Please review the error and try again."
+        exit 1;
+
     fi
 
 
