Update hollaex

diff --git a/hollaex b/hollaex
--- a/hollaex
+++ b/hollaex
@@ -4699,14 +4699,14 @@ elif [[ "$1" == "restart" ]]; then
     done;
 
     # Check the availability of the docker image
-    if ! command docker images | grep $ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY | grep $ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION > /dev/null; then
+    # if ! command docker images | grep $ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY | grep $ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION > /dev/null; then
 
-      echo "Error: The image ($ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY:$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION) is currently not available."
-      echo "This could be an temporary issue, especially when there is a recent Kit release came up just a while ago."
-      echo "Please try it again after a while, or run 'hollaex server --build --local_build' to force build local image."
-      exit 1;
+    #   echo "Error: The image ($ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_REGISTRY:$ENVIRONMENT_USER_HOLLAEX_CORE_IMAGE_VERSION) is currently not available."
+    #   echo "This could be an temporary issue, especially when there is a recent Kit release came up just a while ago."
+    #   echo "Please try it again after a while, or run 'hollaex server --build --local_build' to force build local image."
+    #   exit 1;
     
-    fi
+    # fi
 
     # Update random secrets if env generation is enabled.
     if [[ ! "$IGNORE_SETTINGS" ]]; then 
